// DROP 8 Refactor 027 — Open Arena Recurring Supply Drops
// Windows CMD:
//   node --experimental-strip-types DROP8_refactor_027_open_arena_recurring_supply_drops_patch_FIXED_v1.ts --dry-run
//   node --experimental-strip-types DROP8_refactor_027_open_arena_recurring_supply_drops_patch_FIXED_v1.ts
//   node --experimental-strip-types DROP8_refactor_027_open_arena_recurring_supply_drops_patch_FIXED_v1.ts --rollback
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

type F={path:string;existed:boolean;beforeSha256:string;eol:'LF'|'CRLF';bom:boolean};
type M={patchId:string;patchFile:string;createdAt:string;projectRoot:string;files:F[];createdFiles:string[];generatedDirs:Array<{path:string;existed:boolean}>};
type T={path:string;mode:'modify'|'create';purpose:string;marker:string};
const PATCH_ID='DROP8 Refactor 027 Open Arena Recurring Supply Drops FIXED v1';
const PATCH_FILE='DROP8_refactor_027_open_arena_recurring_supply_drops_patch_FIXED_v1.ts';
const BACKUP_NAME='refactor_027_open_arena_recurring_supply_drops_FIXED_v1';
const MARKER='DROP8_REFACTOR_027_OPEN_ARENA_RECURRING_SUPPLY_DROPS';
const PRIOR_025A='DROP8_REFACTOR_025A_OPEN_ARENA_HUD_LAYOUT_HOTFIX';
const PRIOR_025='DROP8_REFACTOR_025_OPEN_ARENA_KILL_LIMIT_MATCH_CYCLE';
const args=process.argv.slice(2),dryRun=args.includes('--dry-run'),rollbackIndex=args.indexOf('--rollback');
const internal=process.env.DROP8_PATCH_INTERNAL==='1',forceFail=process.env.DROP8_PATCH_FORCE_FAIL==='1';
const scriptDir=dirname(fileURLToPath(import.meta.url));
const sha=(d:Buffer|string)=>createHash('sha256').update(d).digest('hex');
const read=(p:string)=>readFileSync(p,'utf8');
const ts=()=>new Date().toISOString().replace(/[:.]/g,'-');
const eol=(x:string):'LF'|'CRLF'=>x.includes('\r\n')?'CRLF':'LF';
const bom=(x:string)=>x.charCodeAt(0)===0xfeff;
const norm=(p:string)=>p.replace(/\\/g,'/');
function safe(p:string){const r=norm(p);if(!r||r.startsWith('/')||r.split('/').includes('..'))throw new Error('unsafe path '+p);return r;}
function isRoot(p:string){return existsSync(join(p,'package.json'))&&existsSync(join(p,'client/src/GameScene.ts'))&&existsSync(join(p,'server/src/rooms/Drop8Room.ts'))&&existsSync(join(p,'server/src/rooms/openArenaWorld.ts'));}
function root(){for(const start of [process.cwd(),scriptDir]){let c=resolve(start);for(let i=0;i<10;i++){if(isRoot(c))return c;const p=dirname(c);if(p===c)break;c=p;}}throw new Error('DROP8 프로젝트 루트를 찾지 못했습니다.');}
function count(t:string,n:string){return t.split(n).length-1;}
function rep(t:string,a:string,b:string,label:string){const n=count(t,a);if(n!==1)throw new Error(`${label} 문맥 검증 실패: 예상 1회, 실제 ${n}회`);return t.replace(a,b);}
function between(t:string,start:string,end:string,b:string,label:string){const i=t.indexOf(start);if(i<0)throw new Error(`${label} 시작 문맥 없음`);const j=t.indexOf(end,i+start.length);if(j<0)throw new Error(`${label} 끝 문맥 없음`);return t.slice(0,i)+b+t.slice(j);}
function writeAtomic(p:string,c:string){mkdirSync(dirname(p),{recursive:true});const tmp=p+'.drop8-'+process.pid+'-'+Date.now()+'.tmp';writeFileSync(tmp,c,'utf8');renameSync(tmp,p);}
const targets:T[]=[
 {path:'server/src/rooms/openArenaWorld.ts',mode:'modify',marker:`// ${MARKER}`,purpose:'Open Arena 반복 보급 상수 추가'},
 {path:'server/src/rooms/Drop8Room.ts',mode:'modify',marker:`// ${MARKER}`,purpose:'Open Arena 전용 반복 보급 타이머와 다중 보급 제한 추가'},
 {path:'docs/PATCH_NOTES.md',mode:'modify',marker:`<!-- ${MARKER} -->`,purpose:'027 패치 노트 추가'},
 {path:'server/tests/refactor027-open-arena-recurring-supply-drops.test.ts',mode:'create',marker:`// ${MARKER}`,purpose:'027 상수 집중 테스트'},
 {path:'server/tests/refactor027-open-arena-supply-drops-source.test.ts',mode:'create',marker:`// ${MARKER}`,purpose:'027 소스 회귀 테스트'},
];
const constTest=`// ${MARKER}
import { describe,expect,it } from 'vitest';
import { OPEN_ARENA_DROP_TTL_SECONDS,OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS,OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS,OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS,OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS,OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS } from '../src/rooms/openArenaWorld.js';
describe('Refactor 027 Open Arena recurring supply drops',()=>{it('uses bounded recurring supply drop timers without changing existing transient loot cleanup',()=>{expect(OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS).toBe(60);expect(OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS).toBe(90);expect(OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS).toBe(3);expect(OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS).toBe(15);expect(OPEN_ARENA_DROP_TTL_SECONDS).toBe(60);expect(OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS).toBe(1);});});
`;
const sourceTest=`// ${MARKER}
import { describe,expect,it } from 'vitest';import { readFileSync } from 'node:fs';import { resolve } from 'node:path';
const project=resolve(process.cwd(),'..');
const room=readFileSync(resolve(project,'server/src/rooms/Drop8Room.ts'),'utf8');
const world=readFileSync(resolve(project,'server/src/rooms/openArenaWorld.ts'),'utf8');
const notes=readFileSync(resolve(project,'docs/PATCH_NOTES.md'),'utf8');
describe('Refactor 027 Open Arena recurring supply drop source contract',()=>{
  it('is gated behind the 025A chain and Open Arena-only update path',()=>{expect(room).toContain('DROP8_REFACTOR_025_OPEN_ARENA_KILL_LIMIT_MATCH_CYCLE');expect(room).toContain('DROP8_REFACTOR_027_OPEN_ARENA_RECURRING_SUPPLY_DROPS');expect(room).toContain("if(this.gameMode==='battleRoyale')this.updateZone(dt)");expect(room).toContain("if(this.gameMode==='openArena'){this.updateOpenArenaRespawns();this.updateOpenArenaWorld();this.broadcastOpenArenaScoreboard();}");expect(room).toContain("if(this.gameMode!=='openArena'||this.state.phase!=='ACTIVE'||this.openArenaRoundState!=='active')return");});
  it('keeps Battle Royale single-supply semantics while allowing bounded Open Arena recurrence',()=>{expect(room).toContain('private activeSupplyDropCount()');expect(room).toContain('private spawnSupplyDrop(options:{allowMultiple?:boolean;openArenaRecurring?:boolean}={})');expect(room).toContain('if(!recurring&&this.state.supplySpawned)return false');expect(room).toContain('if(recurring&&this.activeSupplyDropCount()>=OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS)return false');expect(room).toContain('if(!recurring)this.state.supplySpawned=true');expect(room).toContain('this.spawnSupplyDrop({allowMultiple:true,openArenaRecurring:true})');expect(room).toContain('this.spawnSupplyDrop();');});
  it('starts and restores the recurring timer across Open Arena lifecycle boundaries',()=>{expect(room).toContain('private openArenaNextSupplyDropAt=0');expect(room.match(/this\\.openArenaNextSupplyDropAt=this\\.now\\(\\)\\+OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS/g)?.length).toBeGreaterThanOrEqual(2);expect(room).toContain('this.openArenaNextSupplyDropAt=0;for(const p of this.state.players.values())');expect(room).toContain('this.openArenaNextSupplyDropAt=now+(spawned?OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS:OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS)');});
  it('documents constants and avoids unrelated 028/029 feature markers',()=>{expect(world).toContain('OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS=60');expect(world).toContain('OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS=3');expect(notes).toContain('Refactor 027 — Open Arena Recurring Supply Drops');expect(room).not.toContain('DROP8_REFACTOR_028_RECURRING_WEREWOLF_RITUAL_CYCLE');expect(room).not.toContain('DROP8_REFACTOR_029_ADHESIVE_FIRE_RATE_SUPPRESSION');});
});
`;
const notesSection=`<!-- ${MARKER} -->
## Refactor 027 — Open Arena Recurring Supply Drops

- Open Arena 전용 반복 보급상자 사이클을 추가했습니다.
- 첫 보급은 상시 전장 라운드 시작 후 60초, 이후 보급은 90초 간격으로 시도합니다.
- 활성 보급상자는 최대 3개로 제한하며, 최대치에 도달하면 해당 주기의 새 보급을 스킵합니다.
- 보급 위치 선정은 기존 보급 위치 검증과 지형·충돌·건물·플레이어 이격 검사를 재사용합니다.
- Battle Royale의 기존 단일 보급, 비행기, 자기장, 전리품 흐름은 유지합니다.
- 라운드 정산/리셋 중에는 새 보급이 발생하지 않으며, 다음 라운드 시작 시 타이머가 다시 예약됩니다.
- 무기 데미지, 발사속도, 이동속도, AI 판단 주기, 서버 Tick, 네트워크 주기는 변경하지 않았습니다.

`;
function patchWorld(x:string){if(x.includes(MARKER))return x;x=rep(x,'// DROP8_REFACTOR_024D_OPEN_ARENA_PERSISTENT_WORLD',`// ${MARKER}\n// DROP8_REFACTOR_024D_OPEN_ARENA_PERSISTENT_WORLD`,'world marker');return rep(x,`export const OPEN_ARENA_DROP_TTL_SECONDS=60;\nexport const OPEN_ARENA_VEHICLE_RESPAWN_SECONDS=75;\nexport const OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS=1;`,`export const OPEN_ARENA_DROP_TTL_SECONDS=60;\nexport const OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS=60;\nexport const OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS=90;\nexport const OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS=3;\nexport const OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS=15;\nexport const OPEN_ARENA_VEHICLE_RESPAWN_SECONDS=75;\nexport const OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS=1;`,'world constants');}
function patchRoom(x:string){if(x.includes(MARKER))return x;
 x=rep(x,'// DROP8_REFACTOR_025_OPEN_ARENA_KILL_LIMIT_MATCH_CYCLE',`// ${MARKER}\n// DROP8_REFACTOR_025_OPEN_ARENA_KILL_LIMIT_MATCH_CYCLE`,'room marker');
 x=rep(x,`import { OPEN_ARENA_DROP_TTL_SECONDS, OPEN_ARENA_VEHICLE_RESPAWN_SECONDS, OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS, arenaLootRespawnSeconds, type ArenaLootSlot, type ArenaVehicleSlot } from './openArenaWorld.js';`,`import { OPEN_ARENA_DROP_TTL_SECONDS, OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS, OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS, OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS, OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS, OPEN_ARENA_VEHICLE_RESPAWN_SECONDS, OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS, arenaLootRespawnSeconds, type ArenaLootSlot, type ArenaVehicleSlot } from './openArenaWorld.js';`,'world import');
 x=rep(x,`  private arenaWorldCleanupAt=0;\n  private arenaKillStreak`,`  private arenaWorldCleanupAt=0;\n  private openArenaNextSupplyDropAt=0;\n  private arenaKillStreak`,'timer field');
 x=rep(x,`this.arenaKillReachedAt.clear();this.openArenaRoundRows=[];for(const p of this.state.players.values())`,`this.arenaKillReachedAt.clear();this.openArenaRoundRows=[];this.openArenaNextSupplyDropAt=0;for(const p of this.state.players.values())`,'dispose timer cleanup');
 x=rep(x,`this.state.zoneActive=false;this.state.zoneState='DISABLED';this.state.supplySpawned=false;this.state.supplyDropId='';`,`this.state.zoneActive=false;this.state.zoneState='DISABLED';this.state.supplySpawned=false;this.state.supplyDropId='';this.openArenaNextSupplyDropAt=this.now()+OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS;`,'begin timer');
 x=rep(x,`if(this.gameMode!=='openArena')return;this.openArenaRoundGeneration++;this.clearTransient();this.humanRespawnAt.clear();this.spawnProtectionUntil.clear();this.clearOpenArenaRoundScores();this.openArenaRoundWinnerId='';this.openArenaRoundRows=[];this.openArenaRoundEndsAt=0;this.openArenaRoundResettingAt=0;`,`if(this.gameMode!=='openArena')return;this.openArenaRoundGeneration++;this.clearTransient();this.humanRespawnAt.clear();this.spawnProtectionUntil.clear();this.clearOpenArenaRoundScores();this.openArenaRoundWinnerId='';this.openArenaRoundRows=[];this.openArenaRoundEndsAt=0;this.openArenaRoundResettingAt=0;this.openArenaNextSupplyDropAt=this.now()+OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS;`,'reset timer');
 const newSpawn="  private activeSupplyDropCount(){let count=0;for(const drop of this.state.supplyDrops.values())if(!drop.opened)count++;return count;}\n\n  private spawnSupplyDrop(options:{allowMultiple?:boolean;openArenaRecurring?:boolean}={}){\n    const recurring=Boolean(options.allowMultiple);if(!recurring&&this.state.supplySpawned)return false;if(recurring&&this.activeSupplyDropCount()>=OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS)return false;\n    const pos=this.findSupplyPosition();if(!pos)return false;const now=this.now(),drop=new SupplyDropState();drop.id=`supply-${++this.supplySeq}`;drop.x=pos.x;drop.y=pos.y;drop.altitude=SUPPLY_DROP_BALANCE.initialAltitude;drop.spawnedAt=now;drop.landedAt=now+SUPPLY_DROP_BALANCE.descentSeconds;drop.landed=false;drop.opened=false;drop.specialWeapon=this.lootRandom()*100<SUPPLY_DROP_BALANCE.flamethrowerWeight?'flamethrower':'bazooka';drop.mapId=this.map.id;drop.zoneStage=this.state.zoneStage;this.state.supplyDrops.set(drop.id,drop);if(!recurring)this.state.supplySpawned=true;this.state.supplyDropId=drop.id;this.emitAudioEvent('supply_incoming',{sourceId:drop.id,x:drop.x,y:drop.y,buildingId:'',variant:drop.specialWeapon});this.system(options.openArenaRecurring?'상시 전장 보급상자가 투하되었습니다.':'보급 상자가 투하되었습니다.');return true;\n  }\n\n  private updateOpenArenaRecurringSupplyDrops(now=this.now()){\n    if(this.gameMode!=='openArena'||this.state.phase!=='ACTIVE'||this.openArenaRoundState!=='active')return;\n    if(this.openArenaNextSupplyDropAt<=0)this.openArenaNextSupplyDropAt=now+OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS;\n    if(now<this.openArenaNextSupplyDropAt)return;\n    if(this.activeSupplyDropCount()>=OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS){this.openArenaNextSupplyDropAt=now+OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS;return;}\n    const spawned=this.spawnSupplyDrop({allowMultiple:true,openArenaRecurring:true});this.openArenaNextSupplyDropAt=now+(spawned?OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS:OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS);\n  }\n\n";
 x=between(x,'  private spawnSupplyDrop(){','  private openNearbySupplyDrop(',newSpawn,'spawn function');
 x=rep(x,`const now=this.now();if(now<this.arenaWorldCleanupAt)return;this.arenaWorldCleanupAt=now+OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS;`,`const now=this.now();if(now<this.arenaWorldCleanupAt)return;this.arenaWorldCleanupAt=now+OPEN_ARENA_WORLD_CLEANUP_INTERVAL_SECONDS;this.updateOpenArenaRecurringSupplyDrops(now);`,'world update hook');
 return x;
}
function exp(root:string,rel:string){if(rel.endsWith('refactor027-open-arena-recurring-supply-drops.test.ts'))return constTest;if(rel.endsWith('refactor027-open-arena-supply-drops-source.test.ts'))return sourceTest;const x=read(join(root,rel));if(rel==='server/src/rooms/openArenaWorld.ts')return patchWorld(x);if(rel==='server/src/rooms/Drop8Room.ts')return patchRoom(x);if(rel==='docs/PATCH_NOTES.md')return x.includes(MARKER)?x:notesSection+x;throw new Error('unknown target '+rel);}
function validateRoot(r:string){const pkg=JSON.parse(read(join(r,'package.json')));if(pkg.name!=='drop8-source')throw new Error('예상 프로젝트가 아닙니다.');const scene=read(join(r,'client/src/GameScene.ts')),css=read(join(r,'client/src/style.css')),notes=read(join(r,'docs/PATCH_NOTES.md')),room=read(join(r,'server/src/rooms/Drop8Room.ts'));if(!scene.includes(PRIOR_025A)||!css.includes(PRIOR_025A)||!notes.includes(PRIOR_025A))throw new Error('025A 마커가 없습니다.');if(!room.includes(PRIOR_025))throw new Error('025 마커가 없습니다.');}
function status(r:string){let a=0,m=0,c:string[]=[];for(const t of targets){const p=join(r,safe(t.path));if(!existsSync(p)){if(t.mode==='create')m++;else c.push(t.path);continue;}const x=read(p);if(x.includes(t.marker))a++;else m++;}return{a,m,c,total:targets.length};}
function precheck(r:string){for(const t of targets){const p=join(r,safe(t.path));if(t.mode==='create'){if(existsSync(p))throw new Error('신규 파일이 이미 존재합니다: '+t.path);}else exp(r,t.path);}}
function verify(r:string){for(const t of targets){const p=join(r,safe(t.path));if(!existsSync(p))throw new Error('파일 누락 '+t.path);if(!read(p).includes(t.marker))throw new Error('마커 누락 '+t.path);}const room=read(join(r,'server/src/rooms/Drop8Room.ts')),world=read(join(r,'server/src/rooms/openArenaWorld.ts')),notes=read(join(r,'docs/PATCH_NOTES.md'));for(const n of ['OPEN_ARENA_SUPPLY_DROP_FIRST_DELAY_SECONDS=60','OPEN_ARENA_SUPPLY_DROP_INTERVAL_SECONDS=90','OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS=3','OPEN_ARENA_SUPPLY_DROP_RETRY_SECONDS=15'])if(!world.includes(n))throw new Error('world 검증 실패 '+n);for(const n of ['private openArenaNextSupplyDropAt=0','private activeSupplyDropCount()','private spawnSupplyDrop(options:{allowMultiple?:boolean;openArenaRecurring?:boolean}={})','private updateOpenArenaRecurringSupplyDrops(now=this.now())','if(!recurring&&this.state.supplySpawned)return false','if(recurring&&this.activeSupplyDropCount()>=OPEN_ARENA_MAX_ACTIVE_SUPPLY_DROPS)return false','if(!recurring)this.state.supplySpawned=true','this.spawnSupplyDrop({allowMultiple:true,openArenaRecurring:true})','this.updateOpenArenaRecurringSupplyDrops(now)'])if(!room.includes(n))throw new Error('room 검증 실패 '+n);if(!room.includes("if(this.gameMode==='battleRoyale')this.updateZone(dt)"))throw new Error('Battle Royale updateZone 경로 누락');if(room.includes('DROP8_REFACTOR_028_RECURRING_WEREWOLF_RITUAL_CYCLE')||room.includes('DROP8_REFACTOR_029_ADHESIVE_FIRE_RATE_SUPPRESSION'))throw new Error('028/029 마커 감지');if(!notes.includes('Refactor 027 — Open Arena Recurring Supply Drops'))throw new Error('notes 누락');}
function backupWrite(r:string){const b=join(r,'patch_backups',BACKUP_NAME,ts()),pre=join(b,'preimage');mkdirSync(pre,{recursive:true});const man:M={patchId:PATCH_ID,patchFile:PATCH_FILE,createdAt:new Date().toISOString(),projectRoot:r,files:[],createdFiles:[],generatedDirs:[]};for(const t of targets){const rel=safe(t.path),p=join(r,rel),ex=existsSync(p);if(ex){const buf=readFileSync(p),bp=join(pre,rel);mkdirSync(dirname(bp),{recursive:true});copyFileSync(p,bp);const txt=buf.toString('utf8');man.files.push({path:rel,existed:true,beforeSha256:sha(buf),eol:eol(txt),bom:bom(txt)});}else{man.files.push({path:rel,existed:false,beforeSha256:'',eol:'LF',bom:false});man.createdFiles.push(rel);}}for(const rel of ['shared/dist','client/dist','server/build']){const p=join(r,rel),ex=existsSync(p);man.generatedDirs.push({path:rel,existed:ex});if(ex){const d=join(b,'generated-preimage',rel);mkdirSync(dirname(d),{recursive:true});cpSync(p,d,{recursive:true,preserveTimestamps:true});}}writeFileSync(join(b,'manifest.json'),JSON.stringify(man,null,2),'utf8');for(const t of targets)writeAtomic(join(r,safe(t.path)),exp(r,t.path));return b;}
function latest(r:string){const base=join(r,'patch_backups',BACKUP_NAME);if(!existsSync(base))throw new Error('백업 폴더 없음');const dirs=readdirSync(base).filter(n=>existsSync(join(base,n,'manifest.json'))).sort().reverse();if(!dirs[0])throw new Error('복원 가능한 백업 없음');return join(base,dirs[0]);}
function roll(r:string,arg?:string){const b=arg?(isAbsolute(arg)?arg:resolve(r,arg)):latest(r),mp=join(b,'manifest.json');const man=JSON.parse(read(mp)) as M;if(man.patchId!==PATCH_ID)throw new Error('다른 패치 백업입니다: '+man.patchId);for(const f of [...man.files].reverse()){const p=join(r,safe(f.path));if(f.existed){const src=join(b,'preimage',safe(f.path));mkdirSync(dirname(p),{recursive:true});copyFileSync(src,p);}else rmSync(p,{force:true});}for(const d of man.generatedDirs){const p=join(r,safe(d.path));rmSync(p,{recursive:true,force:true});if(d.existed){const src=join(b,'generated-preimage',safe(d.path));if(existsSync(src))cpSync(src,p,{recursive:true,preserveTimestamps:true});}}console.log(`[${PATCH_ID}] 롤백 완료: ${b}`);}
function run(label:string,cmd:string,r:string,log:string){console.log(`\n[${PATCH_ID}] ${label}\n> ${cmd}`);const res=spawnSync(cmd,{cwd:r,shell:true,encoding:'utf8',maxBuffer:128*1024*1024,env:process.env});writeFileSync(log,`\n### ${label}\n> ${cmd}\nexit=${res.status}\n${res.stdout??''}\n${res.stderr??''}\n`,{flag:'a'});if(res.stdout)process.stdout.write(res.stdout);if(res.stderr)process.stderr.write(res.stderr);if(res.error)throw res.error;if(res.status!==0)throw new Error(`${label} 실패 (exit=${res.status})`);}
const r=root();process.chdir(r);console.log(`[${PATCH_ID}] 프로젝트 루트: ${r}`);if(rollbackIndex>=0){const arg=args[rollbackIndex+1]&&!args[rollbackIndex+1]!.startsWith('--')?args[rollbackIndex+1]:undefined;roll(r,arg);process.exit(0);}validateRoot(r);const st=status(r);if(st.c.length)throw new Error('파일 누락/충돌: '+st.c.join(', '));if(st.a===st.total){verify(r);console.log(`[${PATCH_ID}] 이미 정상 적용되어 있습니다.`);process.exit(0);}if(st.a>0)throw new Error(`부분 적용 상태(${st.a}/${st.total})입니다.`);precheck(r);console.log(`[${PATCH_ID}] 직전 단계 확인: ${PRIOR_025A}, ${PRIOR_025}`);console.log(`[${PATCH_ID}] 변경 예정 파일:`);for(const t of targets)console.log(` - [${t.mode==='create'?'신규':'수정'}] ${t.path} :: ${t.purpose}`);console.log(`[${PATCH_ID}] 028/029/026은 포함하지 않습니다. Battle Royale 단일 보급·비행기·자기장·전리품·밸런스는 보존합니다.`);if(dryRun){console.log(`\n[${PATCH_ID}] dry-run 성공: 실제 파일과 백업을 만들지 않았습니다.`);process.exit(0);}const b=backupWrite(r),log=join(b,'verification-log.txt');writeFileSync(log,'','utf8');try{verify(r);if(forceFail)throw new Error('DROP8_PATCH_FORCE_FAIL=1 강제 실패');if(!internal){run('TypeScript typecheck','pnpm run typecheck',r,log);run('ESLint','pnpm run lint',r,log);run('Refactor 027 집중 테스트','pnpm --filter @drop8/server exec vitest run tests/refactor027-open-arena-recurring-supply-drops.test.ts tests/refactor027-open-arena-supply-drops-source.test.ts --pool=threads --maxWorkers=1 --no-file-parallelism --testTimeout=30000 --hookTimeout=30000 --reporter=verbose',r,log);run('Open Arena 회귀 테스트','pnpm --filter @drop8/server exec vitest run tests/refactor024a-open-arena-foundation.test.ts tests/refactor024b-open-arena-lifecycle.test.ts tests/refactor024b-join-in-progress.test.ts tests/refactor024c-open-arena-respawn.test.ts tests/refactor024d-arena-loot.test.ts tests/refactor024d-world-cleanup.test.ts tests/refactor024e-arena-scoreboard.test.ts tests/refactor025-open-arena-kill-limit.test.ts tests/refactor025-open-arena-round-source.test.ts tests/refactor025a-open-arena-hud-layout-source.test.ts --pool=threads --maxWorkers=1 --no-file-parallelism --testTimeout=30000 --hookTimeout=30000 --reporter=verbose',r,log);run('Battle Royale 보급/전투 회귀 테스트','pnpm --filter @drop8/server exec vitest run tests/room.test.ts tests/refactor015a-supply-flamethrower.test.ts tests/refactor014-bazooka-slot-plane.test.ts --pool=threads --maxWorkers=1 --no-file-parallelism --testTimeout=30000 --hookTimeout=30000 --reporter=verbose',r,log);run('전체 테스트','pnpm run test',r,log);run('전체 빌드','pnpm run build',r,log);run('대상 git diff check',`git diff --check -- ${targets.map(t=>`"${t.path}"`).join(' ')}`,r,log);}else console.log(`[${PATCH_ID}] 내부 복제본 검증 모드: pnpm 명령 생략`);console.log(`\n[${PATCH_ID}] 적용 성공`);console.log(`[${PATCH_ID}] 백업: ${b}`);console.log(`[${PATCH_ID}] 롤백 CMD: node --experimental-strip-types ${PATCH_FILE} --rollback`);}catch(e){console.error(`\n[${PATCH_ID}] 검증 실패. 전체 자동 롤백합니다.`);try{roll(r,b);}catch(re){console.error('자동 롤백 오류',re);}console.error(`[${PATCH_ID}] 백업: ${b}`);throw e;}
