import { Client, CloseCode, Room } from '@colyseus/core';
import { BulletState, Drop8State, LootState, PlayerState } from './schema.js';
import {
  CHAT_RADIUS, FALL_START_ALTITUDE, LOOT_SPAWNS, MAX_PLAYERS, OBSTACLES, PATCH_RATE_MS, PLANE_DURATION,
  PLAYER_RADIUS, PLAYER_SPEED, SERVER_TICK_RATE, MELEE_WEAPONS, WEAPONS, WORLD_SIZE, circleHitsRect, clamp, createRoomCode,
  distance, isFiniteNumber, sanitizeText, type Difficulty, type LootKind, type MeleeId, type WeaponId, type ZoneSpeed
} from '@drop8/shared';

type Input = { x:number; y:number; angle:number; seq:number };
type AiIntent = { tx:number; ty:number; targetId:string; lootId:string; mode:'move'|'retreat'|'hold'; avoidSign:number; stuckFor:number; lastX:number; lastY:number };
type JoinOptions = { nickname?:unknown; password?:unknown; fillAi?:boolean; difficulty?:Difficulty; zoneSpeed?:ZoneSpeed; roomPassword?:unknown };
const AI_NAMES=['바람','돌멩이','야옹','쏜다','도망','파밍왕','생존봇'];

export class Drop8Room extends Room<{ state: Drop8State }> {
  maxClients=MAX_PLAYERS; state=new Drop8State();
  private inputs=new Map<string,Input>(); private shotAt=new Map<string,number>(); private reloadUntil=new Map<string,number>(); private healUntil=new Map<string,{at:number,amount:number}>();
  private aiThinkAt=new Map<string,number>(); private aiIntent=new Map<string,AiIntent>(); private knockback=new Map<string,{vx:number;vy:number}>(); private chatAt=new Map<string,number>(); private password=''; private elapsed=0; private bulletSeq=0; private lootSeq=0; private planeStart={x:0,y:0}; private planeEnd={x:WORLD_SIZE,y:WORLD_SIZE};

  async onCreate(options:JoinOptions) {
    let code=createRoomCode();
    for(let i=0;i<8 && await this.presence.get(`drop8:${code}`);i++) code=createRoomCode();
    await this.presence.setex(`drop8:${code}`, '1', 60*60*8); this.roomId=code; this.state.roomCode=code;
    this.state.fillAi=options.fillAi !== false; this.state.difficulty=options.difficulty ?? 'normal'; this.state.zoneSpeed=options.zoneSpeed ?? 'normal'; this.password=sanitizeText(options.roomPassword,32);
    this.patchRate=PATCH_RATE_MS; this.setSimulationInterval(dt=>this.tick(dt/1000),1000/SERVER_TICK_RATE);
    this.onMessage('ready',(c)=>this.ready(c)); this.onMessage('settings',(c,m)=>this.settings(c,m)); this.onMessage('start',(c)=>this.start(c));
    this.onMessage('input',(c,m)=>this.input(c,m)); this.onMessage('jump',(c)=>this.jump(c)); this.onMessage('fire',(c)=>this.fire(c)); this.onMessage('melee',(c)=>this.melee(c));
    this.onMessage('reload',(c)=>this.reload(c)); this.onMessage('pickup',(c)=>this.pickup(c)); this.onMessage('switch',(c,m)=>this.switchWeapon(c,m)); this.onMessage('heal',(c,m)=>this.heal(c,m));
    this.onMessage('chat',(c,m)=>this.chat(c,m)); this.onMessage('rematch',(c)=>{if(this.state.phase==='FINISHED' && this.state.players.get(c.sessionId)?.host)this.resetLobby();});
  }

  onAuth(_client:Client, options:JoinOptions) { if(this.password && sanitizeText(options.password,32)!==this.password) throw new Error('비밀번호가 맞지 않습니다.'); return true; }
  onJoin(client:Client, options:JoinOptions) {
    const p=new PlayerState(); p.id=client.sessionId; p.name=sanitizeText(options.nickname,16)||`유저${this.clients.length}`; p.host=this.state.players.size===0;
    this.state.players.set(client.sessionId,p); if(p.host)this.state.hostId=p.id; this.system(`${p.name}님이 입장했습니다.`);
  }
  async onLeave(client:Client, code:CloseCode) {
    const p=this.state.players.get(client.sessionId); if(!p)return;
    if(this.state.phase!=='LOBBY' && code!==CloseCode.CONSENTED) { try { await this.allowReconnection(client,15); return; } catch { /* reconnect timeout */ } }
    const wasHost=p.host; this.state.players.delete(client.sessionId); this.inputs.delete(client.sessionId); this.system(`${p.name}님이 퇴장했습니다.`);
    if(wasHost){ const next=[...this.state.players.values()].find(v=>!v.ai); if(next){next.host=true;this.state.hostId=next.id;} }
  }
  onDispose(){ void this.presence.del(`drop8:${this.roomId}`); }

  private system(text:string){this.broadcast('chat',{channel:'system',sender:'시스템',text,time:Date.now()});}
  private ready(c:Client){const p=this.state.players.get(c.sessionId);if(p&&this.state.phase==='LOBBY'){p.ready=!p.ready;this.system(`${p.name}님이 ${p.ready?'준비했습니다.':'준비를 취소했습니다.'}`);}}
  private settings(c:Client,m:any){const p=this.state.players.get(c.sessionId);if(!p?.host||this.state.phase!=='LOBBY')return; if(typeof m?.fillAi==='boolean')this.state.fillAi=m.fillAi; if(['easy','normal','hard'].includes(m?.difficulty))this.state.difficulty=m.difficulty;if(['slow','normal','fast'].includes(m?.zoneSpeed))this.state.zoneSpeed=m.zoneSpeed;}
  private start(c:Client){const p=this.state.players.get(c.sessionId);if(!p?.host||this.state.phase!=='LOBBY')return;const humans=[...this.state.players.values()].filter(v=>!v.ai);if(humans.some(v=>!v.ready)){c.send('error','모든 실제 플레이어가 준비해야 합니다.');return;} if(this.state.fillAi)this.fillAi();this.beginMatch();}
  private fillAi(){let i=1;while(this.state.players.size<MAX_PLAYERS){const p=new PlayerState();p.id=`ai-${Date.now()}-${i}`;p.name=`AI-${AI_NAMES[(i-1)%AI_NAMES.length]}`;p.ai=true;p.ready=true;this.state.players.set(p.id,p);i++;}}
  private beginMatch(){this.clearTransient();this.elapsed=0;this.state.phase='PLANE';this.state.winner='';this.state.placements.clear();this.state.zoneX=WORLD_SIZE/2;this.state.zoneY=WORLD_SIZE/2;this.state.zoneRadius=1950;this.state.nextZoneRadius=1950;this.state.zoneTimer=30;this.state.zoneStage=0;this.choosePlane();
    let aiIndex=0;for(const p of this.state.players.values()){p.hp=100;p.armor=0;p.alive=true;p.kills=0;p.damageDone=0;p.attackSeq=0;p.hitSeq=0;p.lastHitAngle=0;p.lastHitDamage=0;p.phase='plane';p.altitude=FALL_START_ALTITUDE;p.primary='';p.secondary='';p.melee='fists';p.equipped='fists';p.magazine=0;p.smallAmmo=0;p.rifleAmmo=0;p.shells=0;p.bandages=0;p.medkits=0;p.x=this.planeStart.x;p.y=this.planeStart.y;if(p.ai){this.aiThinkAt.set(p.id,3+aiIndex++*1.7);this.aiIntent.set(p.id,{tx:p.x,ty:p.y,targetId:'',lootId:'',mode:'move',avoidSign:Math.random()<.5?-1:1,stuckFor:0,lastX:p.x,lastY:p.y});}}this.state.aliveCount=this.state.players.size;this.spawnLoot();this.system('비행기가 출발했습니다. Space로 낙하하세요.');}
  private choosePlane(){const horizontal=Math.random()<.5;if(horizontal){const y=400+Math.random()*(WORLD_SIZE-800);this.planeStart={x:0,y};this.planeEnd={x:WORLD_SIZE,y:WORLD_SIZE-y};}else{const x=400+Math.random()*(WORLD_SIZE-800);this.planeStart={x,y:0};this.planeEnd={x:WORLD_SIZE-x,y:WORLD_SIZE};}this.state.planeX=this.planeStart.x;this.state.planeY=this.planeStart.y;this.state.planeEndX=this.planeEnd.x;this.state.planeEndY=this.planeEnd.y;this.state.planeProgress=0;}
  private spawnLoot(){this.state.loot.clear();const weighted:LootKind[]=['pistol','pistol','smg','rifle','shotgun','small_ammo','small_ammo','rifle_ammo','shells','vest','bandage','bandage','medkit','bat','pan','pipe','knife'];for(const spawn of LOOT_SPAWNS){const l=new LootState();l.id=`loot-${++this.lootSeq}`;l.kind=weighted[Math.floor(Math.random()*weighted.length)]!;const pos=this.findLootPosition(spawn.x,spawn.y);l.x=pos.x;l.y=pos.y;this.state.loot.set(l.id,l);}}
  private findLootPosition(baseX:number,baseY:number){for(let i=0;i<18;i++){const radius=i<4?70:70+i*16;const angle=i*2.399963;const x=clamp(baseX+Math.cos(angle)*radius*(i===0?0:1),40,WORLD_SIZE-40);const y=clamp(baseY+Math.sin(angle)*radius*(i===0?0:1),40,WORLD_SIZE-40);if(!OBSTACLES.some(r=>circleHitsRect(x,y,14,r)))return {x,y};}return {x:clamp(baseX,40,WORLD_SIZE-40),y:clamp(baseY,40,WORLD_SIZE-40)};}
  private clearTransient(){this.state.bullets.clear();this.state.loot.clear();this.inputs.clear();this.shotAt.clear();this.reloadUntil.clear();this.healUntil.clear();this.aiIntent.clear();this.knockback.clear();}

  private input(c:Client,m:any){const p=this.state.players.get(c.sessionId);if(!p||p.ai||!p.alive)return;if(!isFiniteNumber(m?.x)||!isFiniteNumber(m?.y)||!isFiniteNumber(m?.angle))return;this.inputs.set(p.id,{x:clamp(m.x,-1,1),y:clamp(m.y,-1,1),angle:m.angle,seq:Number(m.seq)||0});}
  private jump(c:Client){const p=this.state.players.get(c.sessionId);if(p?.phase==='plane')this.doJump(p);}
  private doJump(p:PlayerState){p.phase='falling';p.x=this.state.planeX;p.y=this.state.planeY;p.altitude=FALL_START_ALTITUDE;if(this.state.phase==='PLANE')this.state.phase='DROP';}
  private fire(c:Client){const p=this.state.players.get(c.sessionId);if(p)this.firePlayer(p);}
  private firePlayer(p:PlayerState){if(!p.alive||p.phase!=='landed'||this.reloadUntil.has(p.id)||this.healUntil.has(p.id))return;const w=WEAPONS[p.equipped as WeaponId];if(!w||w.id==='fists'||p.magazine<=0)return;const now=this.clock.elapsedTime/1000;if(now-(this.shotAt.get(p.id)??-99)<w.fireInterval)return;this.shotAt.set(p.id,now);p.attackSeq++;p.magazine--;for(let i=0;i<w.pellets;i++){const a=p.angle+(Math.random()*2-1)*w.spread;const b=new BulletState();b.id=`b-${++this.bulletSeq}`;b.owner=p.id;b.x=p.x+Math.cos(a)*28;b.y=p.y+Math.sin(a)*28;b.vx=Math.cos(a)*w.projectileSpeed;b.vy=Math.sin(a)*w.projectileSpeed;b.life=w.range/w.projectileSpeed;b.damage=w.damage;this.state.bullets.set(b.id,b);}}
  private melee(c:Client){const p=this.state.players.get(c.sessionId);if(!p||!p.alive||p.phase!=='landed')return;const melee=p.equipped==='fists'?{name:'주먹',damage:WEAPONS.fists.damage,fireInterval:WEAPONS.fists.fireInterval,range:WEAPONS.fists.range,arc:1.1}:MELEE_WEAPONS[p.equipped as MeleeId];if(!melee)return;const now=this.clock.elapsedTime/1000;if(now-(this.shotAt.get(p.id)??-99)<melee.fireInterval)return;this.shotAt.set(p.id,now);p.attackSeq++;let target:PlayerState|undefined;let best=melee.range;for(const other of this.state.players.values()){if(!other.alive||other.id===p.id||other.phase!=='landed')continue;const d=distance(p.x,p.y,other.x,other.y);if(d<best&&Math.abs(this.angleDiff(Math.atan2(other.y-p.y,other.x-p.x),p.angle))<melee.arc){target=other;best=d;}}if(target)this.damage(target,melee.damage,p.id,p.equipped==='fists'?'주먹':melee.name);}
  private reload(c:Client){const p=this.state.players.get(c.sessionId);if(!p)return;const w=WEAPONS[p.equipped as WeaponId];if(!w||w.id==='fists'||p.magazine>=w.magazine)return;const reserve=this.getAmmo(p,w.ammoType);if(reserve<=0)return;this.reloadUntil.set(p.id,this.clock.elapsedTime/1000+w.reloadSeconds);}
  private pickup(c:Client){const p=this.state.players.get(c.sessionId);if(!p||p.phase!=='landed'||!p.alive)return;let pick:LootState|undefined,best=72;for(const l of this.state.loot.values()){const d=distance(p.x,p.y,l.x,l.y);if(d<best){best=d;pick=l;}}if(!pick)return;this.applyLoot(p,pick.kind as LootKind);this.state.loot.delete(pick.id);}
  private applyLoot(p:PlayerState,k:LootKind){if(k in WEAPONS&&k!=='fists'){const w=WEAPONS[k as WeaponId];if(w.slot==='primary')p.primary=k;else p.secondary=k;p.equipped=k;p.magazine=w.magazine;if(w.ammoType==='small')p.smallAmmo+=w.magazine*2;if(w.ammoType==='rifle')p.rifleAmmo+=w.magazine*2;if(w.ammoType==='shells')p.shells+=w.magazine*2;return;}if(k in MELEE_WEAPONS){p.melee=k;p.equipped=k;return;}if(k==='small_ammo')p.smallAmmo+=30;else if(k==='rifle_ammo')p.rifleAmmo+=24;else if(k==='shells')p.shells+=12;else if(k==='vest')p.armor=Math.max(p.armor,100);else if(k==='bandage')p.bandages=Math.min(5,p.bandages+1);else if(k==='medkit')p.medkits=Math.min(2,p.medkits+1);}
  private switchWeapon(c:Client,m:any){const p=this.state.players.get(c.sessionId);if(!p)return;const slot=Number(m?.slot);const id=slot===1?p.primary:slot===2?p.secondary:p.melee||'fists';if(!id)return;if(!(id in WEAPONS)&&!(id in MELEE_WEAPONS))return;p.equipped=id;const w=WEAPONS[id as WeaponId];if(w&&w.id!=='fists')p.magazine=Math.min(p.magazine,w.magazine);this.healUntil.delete(p.id);}
  private heal(c:Client,m:any){const p=this.state.players.get(c.sessionId);if(!p||p.hp>=100||this.healUntil.has(p.id))return;const med=m?.kind==='medkit';if(med&&p.medkits>0){p.medkits--;this.healUntil.set(p.id,{at:this.clock.elapsedTime/1000+4,amount:60});}else if(!med&&p.bandages>0){p.bandages--;this.healUntil.set(p.id,{at:this.clock.elapsedTime/1000+2,amount:25});}}
  private chat(c:Client,m:any){const p=this.state.players.get(c.sessionId);if(!p||p.muted)return;const text=sanitizeText(m?.text,80);if(!text)return;const now=Date.now();if(now-(this.chatAt.get(p.id)??0)<650)return;this.chatAt.set(p.id,now);if(this.state.phase==='LOBBY'){this.broadcast('chat',{channel:'lobby',sender:p.name,text,time:now});return;}if(!p.alive){for(const cl of this.clients){const q=this.state.players.get(cl.sessionId);if(q&&!q.alive)cl.send('chat',{channel:'spectator',sender:p.name,text,time:now});}return;}for(const cl of this.clients){const q=this.state.players.get(cl.sessionId);if(q?.alive&&distance(p.x,p.y,q.x,q.y)<=CHAT_RADIUS)cl.send('chat',{channel:'nearby',sender:p.name,text,time:now,playerId:p.id});}}

  private tick(dt:number){if(this.state.phase==='LOBBY'||this.state.phase==='FINISHED')return;this.elapsed+=dt;this.updatePlane(dt);this.updatePlayers(dt);this.updateReloads();this.updateHeals();this.updateBullets(dt);this.updateZone(dt);this.updateAi(dt);this.finishCheck();}
  private updatePlane(_dt:number){if(!['PLANE','DROP'].includes(this.state.phase))return;this.state.planeProgress=clamp(this.elapsed/PLANE_DURATION,0,1);this.state.planeX=this.planeStart.x+(this.planeEnd.x-this.planeStart.x)*this.state.planeProgress;this.state.planeY=this.planeStart.y+(this.planeEnd.y-this.planeStart.y)*this.state.planeProgress;for(const p of this.state.players.values()){if(p.phase==='plane'){p.x=this.state.planeX;p.y=this.state.planeY;if(p.ai && this.elapsed>=(this.aiThinkAt.get(p.id)??8))this.doJump(p);if(this.state.planeProgress>=1)this.doJump(p);}}}
  private updatePlayers(dt:number){for(const p of this.state.players.values()){if(!p.alive)continue;const input=this.inputs.get(p.id)??{x:0,y:0,angle:p.angle,seq:0};if(!p.ai)p.angle=input.angle;if(p.phase==='falling'||p.phase==='parachute'){const parachute=p.altitude<300;p.phase=parachute?'parachute':'falling';const speed=parachute?145:260;const driftX=p.ai?Math.cos(p.angle)*.55:input.x;const driftY=p.ai?Math.sin(p.angle)*.55:input.y;this.tryMove(p,driftX*speed*dt,driftY*speed*dt);p.altitude=Math.max(0,p.altitude-(parachute?120:260)*dt);if(p.altitude<=0){p.phase='landed';this.system(`${p.name} 착지`);}continue;}if(p.phase!=='landed')continue;const kick=this.knockback.get(p.id);if(kick){this.tryMove(p,kick.vx*dt,kick.vy*dt);const damping=Math.pow(.035,dt);kick.vx*=damping;kick.vy*=damping;if(Math.hypot(kick.vx,kick.vy)<8)this.knockback.delete(p.id);}if(p.ai||this.healUntil.has(p.id))continue;const ranged=WEAPONS[(p.equipped||'fists') as WeaponId],melee=MELEE_WEAPONS[p.equipped as MeleeId];const moveMultiplier=ranged?.moveMultiplier??melee?.moveMultiplier??1;this.tryMove(p,input.x*PLAYER_SPEED*moveMultiplier*dt,input.y*PLAYER_SPEED*moveMultiplier*dt);}}
  private tryMove(p:PlayerState,dx:number,dy:number){const beforeX=p.x,beforeY=p.y;const len=Math.hypot(dx,dy);if(len>18){dx=dx/len*18;dy=dy/len*18;}const nx=clamp(p.x+dx,PLAYER_RADIUS,WORLD_SIZE-PLAYER_RADIUS),ny=clamp(p.y+dy,PLAYER_RADIUS,WORLD_SIZE-PLAYER_RADIUS);if(!OBSTACLES.some(r=>circleHitsRect(nx,p.y,PLAYER_RADIUS,r)))p.x=nx;if(!OBSTACLES.some(r=>circleHitsRect(p.x,ny,PLAYER_RADIUS,r)))p.y=ny;return Math.hypot(p.x-beforeX,p.y-beforeY)>.05;}
  private updateReloads(){const now=this.clock.elapsedTime/1000;for(const [id,until] of [...this.reloadUntil])if(now>=until){const p=this.state.players.get(id);if(p){const w=WEAPONS[p.equipped as WeaponId];if(w&&w.id!=='fists'){const need=w.magazine-p.magazine,res=this.getAmmo(p,w.ammoType),load=Math.min(need,res);p.magazine+=load;this.setAmmo(p,w.ammoType,res-load);}}this.reloadUntil.delete(id);}}
  private updateHeals(){const now=this.clock.elapsedTime/1000;for(const [id,h] of [...this.healUntil])if(now>=h.at){const p=this.state.players.get(id);if(p?.alive)p.hp=Math.min(100,p.hp+h.amount);this.healUntil.delete(id);}}
  private updateBullets(dt:number){for(const [id,b] of [...this.state.bullets]){const ox=b.x,oy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0||b.x<0||b.y<0||b.x>WORLD_SIZE||b.y>WORLD_SIZE||OBSTACLES.some(r=>this.segmentRect(ox,oy,b.x,b.y,r))){this.state.bullets.delete(id);continue;}for(const p of this.state.players.values()){if(!p.alive||p.id===b.owner||p.phase!=='landed')continue;if(distance(b.x,b.y,p.x,p.y)<PLAYER_RADIUS+5){this.damage(p,b.damage,b.owner,'총기');this.state.bullets.delete(id);break;}}}}
  private updateZone(dt:number){const landed=[...this.state.players.values()].some(p=>p.phase==='landed');if(!landed)return;const mult=this.state.zoneSpeed==='fast'?1.35:this.state.zoneSpeed==='slow'?.8:1;this.state.zoneTimer-=dt*mult;if(this.state.zoneTimer<=0&&this.state.zoneStage<6){this.state.zoneStage++;this.state.nextZoneRadius=Math.max(120,this.state.zoneRadius*(this.state.zoneStage===1?.68:.72));this.state.zoneTimer=this.state.zoneStage===1?52:42;this.state.zoneX=clamp(this.state.zoneX+(Math.random()-.5)*(this.state.zoneRadius-this.state.nextZoneRadius),this.state.nextZoneRadius,WORLD_SIZE-this.state.nextZoneRadius);this.state.zoneY=clamp(this.state.zoneY+(Math.random()-.5)*(this.state.zoneRadius-this.state.nextZoneRadius),this.state.nextZoneRadius,WORLD_SIZE-this.state.nextZoneRadius);}if(this.state.nextZoneRadius<this.state.zoneRadius)this.state.zoneRadius=Math.max(this.state.nextZoneRadius,this.state.zoneRadius-dt*(28+this.state.zoneStage*16)*mult);for(const p of this.state.players.values()){if(p.alive&&p.phase==='landed'&&distance(p.x,p.y,this.state.zoneX,this.state.zoneY)>this.state.zoneRadius)this.damage(p,(2+this.state.zoneStage*1.8)*dt,'','자기장');}}
  private updateAi(dt:number){const now=this.clock.elapsedTime/1000;for(const p of this.state.players.values()){if(!p.ai||!p.alive||p.phase!=='landed')continue;let intent=this.aiIntent.get(p.id);if(!intent){intent={tx:this.state.zoneX,ty:this.state.zoneY,targetId:'',lootId:'',mode:'move',avoidSign:Math.random()<.5?-1:1,stuckFor:0,lastX:p.x,lastY:p.y};this.aiIntent.set(p.id,intent);}if(now>=(this.aiThinkAt.get(p.id)??0)){this.aiThinkAt.set(p.id,now+(this.state.difficulty==='hard'?.14:this.state.difficulty==='easy'?.34:.22));this.planAi(p,intent);}this.runAi(p,intent,dt);}}
  private planAi(p:PlayerState,intent:AiIntent){intent.targetId='';intent.lootId='';intent.mode='move';const outside=distance(p.x,p.y,this.state.zoneX,this.state.zoneY)>this.state.zoneRadius-180;if(outside){intent.tx=this.state.zoneX;intent.ty=this.state.zoneY;return;}if(!p.primary&&!p.secondary){let chosen:LootState|undefined,best=Number.POSITIVE_INFINITY;for(const l of this.state.loot.values()){if(!['pistol','smg','rifle','shotgun'].includes(l.kind))continue;const d=distance(p.x,p.y,l.x,l.y);if(d<best){best=d;chosen=l;}}if(chosen){intent.lootId=chosen.id;intent.tx=chosen.x;intent.ty=chosen.y;return;}}let target:PlayerState|undefined,best=900;for(const q of this.state.players.values()){if(q.id===p.id||!q.alive||q.phase!=='landed')continue;const d=distance(p.x,p.y,q.x,q.y);if(d<best&&!OBSTACLES.some(r=>this.segmentRect(p.x,p.y,q.x,q.y,r))){best=d;target=q;}}if(target){intent.targetId=target.id;const desired=p.equipped==='shotgun'?175:p.equipped==='smg'?260:390;if(best>desired*1.15){intent.mode='move';intent.tx=target.x;intent.ty=target.y;}else if(best<desired*.55){intent.mode='retreat';intent.tx=p.x-(target.x-p.x);intent.ty=p.y-(target.y-p.y);}else{intent.mode='hold';intent.tx=target.x;intent.ty=target.y;}return;}let useful:LootState|undefined,bestLoot=650;for(const l of this.state.loot.values()){const d=distance(p.x,p.y,l.x,l.y);if(d<bestLoot){bestLoot=d;useful=l;}}if(useful){intent.lootId=useful.id;intent.tx=useful.x;intent.ty=useful.y;}else{intent.tx=this.state.zoneX+(Math.random()-.5)*Math.min(500,this.state.zoneRadius*.4);intent.ty=this.state.zoneY+(Math.random()-.5)*Math.min(500,this.state.zoneRadius*.4);}}
  private runAi(p:PlayerState,intent:AiIntent,dt:number){const target=intent.targetId?this.state.players.get(intent.targetId):undefined;if(target?.alive){intent.tx=target.x;intent.ty=target.y;p.angle=Math.atan2(target.y-p.y,target.x-p.x);this.firePlayer(p);}const loot=intent.lootId?this.state.loot.get(intent.lootId):undefined;if(loot&&distance(p.x,p.y,loot.x,loot.y)<72){this.applyLoot(p,loot.kind as LootKind);this.state.loot.delete(loot.id);intent.lootId='';this.aiThinkAt.set(p.id,0);}if(intent.mode==='hold'){if(target){const side=p.angle+Math.PI/2*intent.avoidSign;this.tryMove(p,Math.cos(side)*72*dt,Math.sin(side)*72*dt);}return;}let angle=Math.atan2(intent.ty-p.y,intent.tx-p.x);if(intent.mode==='retreat'&&target)angle=Math.atan2(p.y-target.y,p.x-target.x);p.angle=target?Math.atan2(target.y-p.y,target.x-p.x):angle;const speed=this.state.difficulty==='hard'?235:this.state.difficulty==='easy'?175:205;let moved=this.tryMove(p,Math.cos(angle)*speed*dt,Math.sin(angle)*speed*dt);if(!moved){const side=angle+intent.avoidSign*Math.PI/2;moved=this.tryMove(p,Math.cos(side)*speed*.9*dt,Math.sin(side)*speed*.9*dt);if(!moved){intent.avoidSign*=-1;const other=angle+intent.avoidSign*Math.PI/2;this.tryMove(p,Math.cos(other)*speed*.85*dt,Math.sin(other)*speed*.85*dt);}}const progress=distance(p.x,p.y,intent.lastX,intent.lastY);intent.stuckFor=progress<1?intent.stuckFor+dt:Math.max(0,intent.stuckFor-dt*2);if(intent.stuckFor>.65){intent.avoidSign*=-1;intent.tx=clamp(p.x+Math.cos(angle+intent.avoidSign*Math.PI/2)*220,PLAYER_RADIUS,WORLD_SIZE-PLAYER_RADIUS);intent.ty=clamp(p.y+Math.sin(angle+intent.avoidSign*Math.PI/2)*220,PLAYER_RADIUS,WORLD_SIZE-PLAYER_RADIUS);intent.stuckFor=0;}intent.lastX=p.x;intent.lastY=p.y;}
  private damage(p:PlayerState,amount:number,attackerId:string,reason:string){if(!p.alive)return;this.healUntil.delete(p.id);let actual=amount;if(p.armor>0&&reason==='총기'){const absorbed=actual*.3;actual-=absorbed;p.armor=Math.max(0,p.armor-absorbed*1.5);}const attacker=this.state.players.get(attackerId);const hitAngle=attacker?Math.atan2(p.y-attacker.y,p.x-attacker.x):p.lastHitAngle;p.hitSeq++;p.lastHitAngle=hitAngle;p.lastHitDamage=actual;if(attacker&&reason!=='자기장'){const power=this.knockbackPower(attacker,reason);if(power>0){const current=this.knockback.get(p.id)??{vx:0,vy:0};current.vx+=Math.cos(hitAngle)*power;current.vy+=Math.sin(hitAngle)*power;const max=420,len=Math.hypot(current.vx,current.vy);if(len>max){current.vx=current.vx/len*max;current.vy=current.vy/len*max;}this.knockback.set(p.id,current);}}p.hp-=actual;if(attacker)attacker.damageDone+=actual;if(p.hp<=0){p.hp=0;p.alive=false;p.phase='dead';this.knockback.delete(p.id);this.aiIntent.delete(p.id);this.state.placements.unshift(p.name);if(attacker&&attacker.id!==p.id){attacker.kills++;this.broadcast('killfeed',{killer:attacker.name,victim:p.name,reason});}else this.broadcast('killfeed',{killer:reason,victim:p.name,reason});this.dropInventory(p);}}
  private knockbackPower(attacker:PlayerState,reason:string){if(reason==='주먹')return 230;if(reason==='야구방망이')return 320;if(reason==='프라이팬')return 360;if(reason==='쇠파이프')return 285;if(reason==='식칼')return 165;if(reason==='총기'){return attacker.equipped==='shotgun'?230:attacker.equipped==='rifle'?90:attacker.equipped==='pistol'?72:38;}return 0;}
  private dropInventory(p:PlayerState){const kinds=[p.primary,p.secondary,p.melee!=='fists'?p.melee:'',p.armor>0?'vest':'',p.bandages?'bandage':'',p.medkits?'medkit':''].filter(Boolean);for(const k of kinds){const l=new LootState();l.id=`loot-${++this.lootSeq}`;l.kind=k;l.x=clamp(p.x+(Math.random()-.5)*55,20,WORLD_SIZE-20);l.y=clamp(p.y+(Math.random()-.5)*55,20,WORLD_SIZE-20);this.state.loot.set(l.id,l);}}
  private finishCheck(){const alive=[...this.state.players.values()].filter(p=>p.alive);this.state.aliveCount=alive.length;if(alive.length<=1&&this.state.players.size>1&&this.state.phase!=='FINISHED'){this.state.phase='FINISHED';this.state.winner=alive[0]?.name??'없음';if(alive[0])this.state.placements.unshift(alive[0].name);this.broadcast('result',{winner:this.state.winner,placements:[...this.state.placements]});}}
  private resetLobby(){this.clearTransient();for(const [id,p] of [...this.state.players]){if(p.ai)this.state.players.delete(id);else{p.ready=false;p.alive=true;p.hp=100;p.phase='lobby';p.primary='';p.secondary='';p.melee='fists';p.equipped='fists';p.attackSeq=0;p.hitSeq=0;p.lastHitAngle=0;p.lastHitDamage=0;}}this.state.phase='LOBBY';this.state.winner='';this.state.placements.clear();this.state.aliveCount=this.state.players.size;}
  private getAmmo(p:PlayerState,t:string){return t==='small'?p.smallAmmo:t==='rifle'?p.rifleAmmo:t==='shells'?p.shells:0;}
  private setAmmo(p:PlayerState,t:string,v:number){if(t==='small')p.smallAmmo=v;else if(t==='rifle')p.rifleAmmo=v;else if(t==='shells')p.shells=v;}
  private angleDiff(a:number,b:number){return Math.atan2(Math.sin(a-b),Math.cos(a-b));}
  private segmentRect(x1:number,y1:number,x2:number,y2:number,r:{x:number;y:number;w:number;h:number}){const steps=Math.max(1,Math.ceil(distance(x1,y1,x2,y2)/18));for(let i=0;i<=steps;i++){const t=i/steps,x=x1+(x2-x1)*t,y=y1+(y2-y1)*t;if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h)return true;}return false;}
}
